import { NextRequest, NextResponse } from 'next/server'

export const runtime = 'edge'

export async function GET(request: NextRequest) {
  const url = request.nextUrl.searchParams.get('url')
  if (!url) return NextResponse.json({ success: false, error: 'URL required' }, { status: 400 })

  let targetUrl = url
  if (!targetUrl.startsWith('http')) targetUrl = 'https://' + targetUrl

  try {
    const controller = new AbortController()
    const timeout = setTimeout(() => controller.abort(), 10000)
    const res = await fetch(targetUrl, { signal: controller.signal, redirect: 'follow', headers: { 'User-Agent': 'SecHeaders/1.0' } })
    clearTimeout(timeout)

    const headers: Record<string, string> = {}
    res.headers.forEach((v, k) => { const l = k.toLowerCase(); headers[l] = headers[l] ? headers[l] + ', ' + v : v })

    const { analyzeHeaders, gradeFromScore } = await import('@/lib/headers')
    const { checks, overallScore, maxScore } = analyzeHeaders(headers)
    const grade = gradeFromScore(overallScore, maxScore)

    const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>SecHeaders Report — ${targetUrl}</title>
<style>
  body { font-family: -apple-system, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; color: #1a1a2e; }
  h1 { font-size: 24px; margin-bottom: 4px; }
  .meta { color: #666; font-size: 14px; margin-bottom: 20px; }
  .grade { font-size: 48px; font-weight: 800; margin: 16px 0; }
  .grade.A { color: #059669; } .grade.B { color: #16a34a; } .grade.C { color: #ca8a04; }
  .grade.D { color: #ea580c; } .grade.E { color: #dc2626; } .grade.F { color: #b91c1c; }
  table { width: 100%; border-collapse: collapse; margin-top: 20px; }
  th, td { padding: 8px 12px; text-align: left; border-bottom: 1px solid #e2e8f0; font-size: 13px; }
  th { background: #f8fafc; font-weight: 600; }
  .present { color: #059669; } .missing { color: #dc2626; }
  .footer { margin-top: 30px; text-align: center; color: #94a3b8; font-size: 11px; }
  .score-bar { height: 8px; background: #e2e8f0; border-radius: 4px; margin: 8px 0; }
  .score-fill { height: 8px; border-radius: 4px; }
</style></head><body>
  <h1>Security Headers Report</h1>
  <div class="meta">${targetUrl} &middot; HTTP ${res.status} &middot; ${new Date().toISOString().split('T')[0]}</div>
  <div class="grade ${grade}">${grade} &middot; ${overallScore}/${maxScore}</div>
  <div class="score-bar"><div class="score-fill" style="width:${Math.round(overallScore / maxScore * 100)}%;background:${grade === 'A' ? '#059669' : grade === 'F' ? '#b91c1c' : '#ca8a04'}"></div></div>
  <table><tr><th>Header</th><th>Value</th><th>Score</th></tr>
  ${checks.map((c: any) => `<tr><td><strong>${c.displayName}</strong></td><td class="${c.value ? 'present' : 'missing'}">${c.value || 'MISSING'}</td><td>${c.score}/${c.maxScore}</td></tr>`).join('')}
  </table>
  <div class="footer">Generated by SecHeaders &mdash; secheaders.vercel.app</div>
</body></html>`

    return new NextResponse(html, {
      headers: { 'Content-Type': 'text/html', 'Content-Disposition': `inline; filename="secheaders-report-${targetUrl.replace(/[^a-z0-9]/gi, '_')}.html"` },
    })
  } catch (err) {
    return NextResponse.json({ success: false, error: err instanceof Error ? err.message : 'Failed' }, { status: 500 })
  }
}
